---
all:
  children:
    panorama:
      hosts:
        panorama-primary:
          ansible_host: panorama.corp.example.com
          panorama_role: primary
        panorama-secondary:
          ansible_host: panorama-ha.corp.example.com
          panorama_role: secondary

    aws_vmseries:
      hosts:
        vmseries-aws-01:
          ansible_host: "{{ lookup('env', 'VMSERIES_01_MGMT_IP') }}"
          panos_role: active
          az: us-east-1a
          device_group: aws-vmseries-prod
          template_stack: aws-vmseries-template-stack
        vmseries-aws-02:
          ansible_host: "{{ lookup('env', 'VMSERIES_02_MGMT_IP') }}"
          panos_role: passive
          az: us-east-1b
          device_group: aws-vmseries-prod
          template_stack: aws-vmseries-template-stack

    dc_firewalls:
      hosts:
        pa-dc-01:
          ansible_host: 10.0.1.1
          panos_role: active
          site: datacenter
          device_group: dc-perimeter
          template_stack: dc-perimeter-template-stack
        pa-dc-02:
          ansible_host: 10.0.1.2
          panos_role: passive
          site: datacenter
          device_group: dc-perimeter
          template_stack: dc-perimeter-template-stack
