---
# Baseline tasks notify "Commit config" after any changes
- name: Commit config
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ panos_provider }}"
    description: "Baseline hardening commit"
