---
# HA tasks notify "Commit HA config" after any changes
- name: Commit HA config
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ panos_provider }}"
    description: "HA configuration commit"
