---
# Threat profile tasks notify this handler when changed
- name: Commit threat profiles
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ panos_provider }}"
    description: "Threat prevention profiles commit"
