---
panos_vpn_dc_edge_public_ip: "203.0.113.10"
panos_vpn_dc_edge_tunnel_ip: "169.254.0.2"
panos_vpn_tunnel_local_ip: "169.254.0.1/30"
panos_vpn_virtual_router: "default"
panos_vpn_dc_subnets:
  - "10.100.0.0/16"
  - "10.101.0.0/16"
