#!/usr/bin/env python3
"""report_generator.py — HTML and CSV report output utilities."""

import csv
import io
from datetime import datetime
from typing import List, Dict, Any


def generate_html_report(title: str, sections: List[Dict[str, Any]], metadata: Dict[str, str] = None) -> str:
    """Generate a styled HTML report from sections of findings."""
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    meta_html = ""
    if metadata:
        meta_html = "".join(f"<li><strong>{k}:</strong> {v}</li>" for k, v in metadata.items())
        meta_html = f"<ul class=\"meta\">{meta_html}</ul>"

    sections_html = ""
    for section in sections:
        rows = ""
        if section.get("rows"):
            headers = section.get("headers", [])
            header_row = "".join(f"<th>{h}</th>" for h in headers)
            for row in section["rows"]:
                cells = "".join(f"<td>{c}</td>" for c in row)
                rows += f"<tr>{cells}</tr>"
            sections_html += f"""
            <section>
              <h2>{section['title']}</h2>
              <p>{section.get('description', '')}</p>
              <table><thead><tr>{header_row}</tr></thead><tbody>{rows}</tbody></table>
            </section>"""
        else:
            sections_html += f"""
            <section>
              <h2>{section['title']}</h2>
              <p>{section.get('description', 'No findings.')}</p>
            </section>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{title}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; margin: 2rem; color: #1a1a2e; }}
    h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 0.5rem; }}
    h2 {{ color: #0f3460; margin-top: 2rem; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 1rem; }}
    th {{ background: #0f3460; color: white; padding: 0.75rem; text-align: left; }}
    td {{ padding: 0.6rem; border-bottom: 1px solid #ddd; }}
    tr:nth-child(even) {{ background: #f8f9fa; }}
    .meta {{ list-style: none; padding: 0; display: flex; gap: 2rem; flex-wrap: wrap; }}
    .meta li {{ background: #f0f4ff; padding: 0.4rem 0.8rem; border-radius: 4px; }}
    .footer {{ margin-top: 3rem; font-size: 0.8rem; color: #666; border-top: 1px solid #ddd; padding-top: 1rem; }}
    .badge-pass {{ color: #1a7a4a; font-weight: bold; }}
    .badge-fail {{ color: #c0392b; font-weight: bold; }}
    .badge-warn {{ color: #e67e22; font-weight: bold; }}
  </style>
</head>
<body>
  <h1>{title}</h1>
  <p>Generated: {now}</p>
  {meta_html}
  {sections_html}
  <div class="footer">Generated by paloalto-enterprise-firewall-automation | maheshkotlacv-sys</div>
</body>
</html>"""


def generate_csv_report(headers: List[str], rows: List[List[Any]]) -> str:
    """Return CSV content as a string."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(headers)
    writer.writerows(rows)
    return output.getvalue()
